package:
  name: quantlib
  version: 1.22
  
source:
  url: https://github.com/lballabio/QuantLib/archive/QuantLib-1.22.tar.gz
  
requirements:
  build:
    #noarch: generic
    - automake
    - autoconf
    - libtool
    - boost
  run:

about:
  home: http://www.quantlib.org/
  license: https://github.com/lballabio/QuantLib/blob/master/LICENSE.TXT
  summary: "QuantLib: A free/open-source library for quantitative finance"
