version: "3.7"

services:
  nbanalysis:
      build:
        context: .
        dockerfile: DockerFile
      image: nb_flutter
      container_name: nb_flutter
      environment:
        TZ: "America/new_york"
      ports:
        - "8383:8383"
      volumes:
        - /data/code/projects/notebook:/home/jupyter/notebook
        - /etc/localtime:/etc/localtime:ro

#    nbquantlib:
#    build:
#      context: .
#      dockerfile: DockerFile
#    image: neutron_binary_quantlib
#    container_name: neutron_binary_quantlib
#    environment:
#      TZ: "America/new_york"
#    ports:
#      - "9999:9999"
#    volumes:
#       - /data/code/projects/notebook:/home/jupyter/notebook
 #      - /etc/localtime:/etc/localtime:ro