version: "3.7"

services:
  nbanalysis:
      build:
        context: .
        dockerfile: Dockerfile.Prophet
      image: nb_prophet
      container_name: nb_prophet
      environment:
        TZ: "America/new_york"
      ports:
        - "8282:8282"
      volumes:
        - /data/code/projects/notebook:/home/jupyter/notebook
        - /data/code/projects/environments:/home/jupyter/environments
        - /etc/localtime:/etc/localtime:ro

#    nbquantlib:
#    build:
#      context: .
#      dockerfile: DockerFile
#    image: neutron_binary_quantlib
#    container_name: neutron_binary_quantlib
#    environment:
#      TZ: "America/new_york"
#    ports:
#      - "9999:9999"
#    volumes:
#       - /data/code/projects/notebook:/home/jupyter/notebook
 #      - /etc/localtime:/etc/localtime:ro