package:
  name: quantlib-python
  version: 1.22
  
source:
  url: https://github.com/lballabio/QuantLib-SWIG/archive/QuantLib-SWIG-v1.19.tar.gz

requirements:
  build:
    - autoconf
    - swig >=4.0.2
    - python >=3.7
    - numpy >=1.19.0
    - pystan == 2.19.1.1
    - fbprophet >= 0.7.1
    - c3pyo >= 0.0.4.1
  run:
    - python

about:
  home: http://www.quantlib.org/
  license: https://github.com/lballabio/QuantLib-SWIG/blob/master/LICENSE.TXT
  summary: "QuantLib-Python: Python binding for QuantLib"
