version: "3.7"

services:
  quantlib:
    build:
      context: ../../../../../../home/lakhwindersingh/PycharmProjects/ORM_Docker
      dockerfile: Dockerfile
    image: nb_quantlib
    container_name: nb_quantlib
    environment:
      TZ: "America/new_york"
    ports:
      - "9999:9999"
    volumes:
      - ./notebook:/home/jupyter/notebook
      - /etc/localtime:/etc/localtime:ro
