version: "3.7"

services:
  cube:
    image: cubejs/cube:latest
    ports:
        - 4000:4000
        - 15432:15432
    environment:
        - CUBEJS_DEV_MODE=true
    volumes:
        - .:/cube/conf
        - /Users/lakhwinder/data/projects:/home/projects
        - /etc/localtime:/etc/localtime:ro
